app/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

   root 'welcome#index'

     resources :parks do
       resources :comments
     end

end

app/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :park
end

app/app/models/park.rb
class Park < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

   http_basic_authenticate_with name: "admin", password: "admin", only: :destroy

  def create
    @park = Park.find(params[:park_id])
    @comment = @park.comments.create(comment_params)
    redirect_to park_path(@park)
  end

  def destroy
    @park = Park.find(params[:park_id])
    @comment = @park.comments.find(params[:id])
    @comment.destroy
   redirect_to park_path(@park)
  end

private
 def comment_params
   params.require(:comment).permit(:commenter, :body)
 end
end

app/app/controllers/parks_controller.rb
class ParksController < ApplicationController

  http_basic_authenticate_with name: "admin", password: "admin", except: [:index, :show]

  def index
    @parks = Park.all
  end

  def show
    @park = Park.find(params[:id])
  end

  def new
    @park = Park.new
  end

  def edit
    @park = Park.find(params[:id])
  end

  def create
    @park = Park.new(park_params)

    if @park.save
      redirect_to @park
    else
      render 'new'
    end
  end

  def update
    @park = Park.find(params[:id])

    if @park.update(park_params)
      redirect_to @park
    else
      render 'edit'
    end
  end

  def destroy
    @park = Park.find(params[:id])
    @park.destroy

 redirect_to parks_path
  end

  private
  def park_params
    params.require(:park).permit(:title, :text)
  end

end

app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/app/helpers/application_helper.rb
module ApplicationHelper
end

app/app/helpers/comments_helper.rb
module CommentsHelper
end

app/app/helpers/parks_helper.rb
module ParksHelper
end

app/app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.park, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/app/views/comments/_form.html.erb
<%= form_for([@park, @park.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/app/views/parks/_form.html.erb
<%= form_for @park do |f| %>

  <% if @park.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@park.errors.count, "error") %> prohibited
        this park from being saved:
      </h2>
      <ul>
        <% @park.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/app/views/parks/edit.html.erb
<h1>Editing park</h1>

<%= render 'form' %>

<%= link_to 'Back', park_path %>

app/app/views/parks/index.html.erb
<h1>Listing parks</h1>
<%= link_to 'New park', new_park_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>

  <% @parks.each do |park| %>
    <tr>
      <td><%= park.title %></td>
      <td><%= park.text %></td>
      <td><%= link_to 'Show', park_path(park) %></td>
      <td><%= link_to 'Edit', edit_park_path(park) %></td>
      <td><%= link_to 'Destroy', park_path(park),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/app/views/parks/new.html.erb
<h1>New Park</h1>

<%= render 'form' %>

<%= link_to 'Back', parks_path %>

app/app/views/parks/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @park.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @park.text %>
</p>

<h2>Comments</h2>
<% render @park.comments %>


<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Back', parks_path %>
<%= link_to 'Edit', edit_park_path(@park) %>

app/app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'parks' %>